# Generated by Django 4.2 on 2025-09-12 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.CharField(default='📝', help_text='Emoji icon for the post', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(default=3, help_text='Estimated reading time in minutes'),
        ),
    ]
